version: "3"

services: 

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    restart: always
    volumes:
      - ./:/usr/share/nginx/html/
    ports:
      - 80:80
    depends_on:
      - bigchaindb
    command: nginx -g 'daemon off';

  # Build: docker-compose build -d bigchaindb
  # Run: docker-compose run -d bdb
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod
  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    build:
      context: ./bigchaindb/
      dockerfile: ./bigchaindb/Dockerfile-dev
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb/bigchaindb:/usr/src/app/bigchaindb
      - ./bigchaindb/tests:/usr/src/app/tests
      - ./bigchaindb/docs:/usr/src/app/docs
      - ./bigchaindb/htmlcov:/usr/src/app/htmlcov
      - ./bigchaindb/setup.py:/usr/src/app/setup.py
      - ./bigchaindb/setup.cfg:/usr/src/app/setup.cfg
      - ./bigchaindb/pytest.ini:/usr/src/app/pytest.ini
      - ./bigchaindb/tox.ini:/usr/src/app/tox.ini
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 46657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "46658"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://bigchaindb:9984 && curl http://tendermint:46657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 3
    command: './bigchaindb/ci/entrypoint.sh'
  tendermint:
    image: tendermint/tendermint:0.19.9
    # volumes:
    #   - ./tmdata:/tendermint
    entrypoint: ''
    ports:
      - "46656:46656"
      - "46657:46657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:46658"
  bdb:
    image: busybox
    depends_on:
      bigchaindb:
        condition: service_healthy


  # curl client to check the health of development env
  curl-client:
    image: appropriate/curl
    command: /bin/sh -c "curl -s http://bigchaindb:9984/ > /dev/null && curl -s http://tendermint:46657/ > /dev/null"

  # BigchainDB setup to do acceptance testing with Python
  python-acceptance:
    build:
      context: ./bigchaindb/
      dockerfile: ./bigchaindb/acceptance/python/Dockerfile
    volumes:
      - ./bigchaindb/acceptance/python/docs:/docs
      - ./bigchaindb/acceptance/python/src:/src
    environment:
      - BIGCHAINDB_ENDPOINT=bigchaindb

  # Build docs only
  # docker-compose build bdocs
  # docker-compose up -d bdocs
  bdocs:
    depends_on:
      - vdocs
    build:
      context: ./bigchaindb/
      dockerfile: ./bigchaindb/Dockerfile-dev
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb/:/usr/src/app/
    command: make -C docs/server html
  vdocs:
    image: nginx
    ports:
      - '33333:80'
    volumes:
      - ./bigchaindb/docs/server/build/html:/usr/share/nginx/html